# Generated by Django 5.0.6 on 2026-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=1)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('dealer_handle', models.CharField(help_text='Enter Instagram username or full WhatsApp link (e.g., @big_steph or https://wa.me/xxx)', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
